# name: ori hirshfeld
# id: 201085776
#name Amichai Wollin
# id: 300582392

a.out:	ReversiServer.o main.o
	g++	ReversiServer.o main.o

main.o:	main.cpp
	g++ -c main.cpp

ReversiServer.o:	ReversiServer.cpp ReversiServer.h
	g++ -c ReversiServer.cpp
